### ISSUE TITLE
Support MySQL database

### ISSUE THREAD

**Issue by rsertelon** [anotheria/moskito-central#10]
Hi,

We've tried to use Central for we are deploying moskito to monitor our applications.

There seems to be no support for MySQL as the JPA ID Generator use Sequence, which is not supported by MySQL.

Is it possible to widen supported databases by changing the model a bit?

BTW, do you look for help? We could help with the maintenance of Moskito Central, and maybe more.

Do you accept PRs ? ;)

Cheers,

**Comment by dvayanu** [comment]
Hi Romain,
we will be very happy to receive a PR from you ;-) As long as it doesn't break existing functionality of course. There is a lot of work to do with MoSKito Central so if you want to help, we always welcome help!  Do you have something in mind, what you think is missing in MoSKito?
regards
Leon

**Comment by rsertelon** [comment]
Hi,

First, it could be MySQL support ;)

Then, we could help with several 'issues':

* Configuration outside of war => Not ideal to have to rebuild a war to configure it
* Simplification of the maven build, and cleanup of the sources. Can't list the issues here, will make a PR with cherry-pickable commits you want :)

There would be other ideas coming up once we will try to help fix some :)

Also I like the idea of Moskito Control, however, I think that we should have the agents connect to Control, not the other way around. It's not very practical in a cloud environment where instances are likely to be dropped/created automatically.

I will take some time (with my colleagues) to propose features/evolutions that we will judge interesting, and we'll be happy to discuss them with you via Github issues and PRs.

**Comment by rsertelon** [comment]
BTW, if you have a backlog in mind, wouldn't it be nice to create issues for its items? We could also help you with these... :)

**Comment by dvayanu** [comment]
Hi Romain,
as for backlog/issue tracking we usually use jira for this: https://jira.opensource.anotheria.net and in particular https://jira.opensource.anotheria.net/browse/MSKCENTRAL for MoSKito Central (most issues are opened for MoSKito Core components though). 

As for MoSKito Control, I understand your point of view and Thomas already wrote about it some time ago. I think the main reason we are doing a pull instead of a push, is to have additional information about the ability to connect. In case control can't connect to a component you can get much faster feedback and report a problem as if you would be waiting for some timeouts.

But I think (and I wrote to Thomas some time ago), that it could absolutely make sense to create an auto-connect plugin for elastic environments, which would allow dynamically started components to register and unregister themselves. 

I think it makes more sense to discuss some of this stuff in a more interactive format like irc or skype at some point ;) What do you think?

regards
Leon

**Comment by rsertelon** [comment]
We'll look into your jira tracker then.

Indeed both mechanisms seems to be complementary.

I'm looking forward to chat indeed, but I have to have a closer look to every topics we discussed so I can actually be of some help ;)

I'll get back to you, hopefully next week.

Thanks !

**Comment by dvayanu** [comment]
Hi,
it has been a while.
do you have any new development regarding this issue? ;-)

**Comment by rsertelon** [comment]
Hi Leon,

Sorry for the delay of my answer. Since we've started to have a look into Moskito, there has been change in how we will monitor our applications. I'm sorry but we won't be using Moskito anylonger.

Thus, investing time in it is not a priority anymore.

Thanks for your help anyways and good luck with Moskito!

Cheers,

**Comment by dvayanu** [comment]
Sorry to hear that!

**Comment by dvayanu** [comment]
Should close the issue than ;-)
